### ISSUE TITLE
Using "reply.send()" in async error handler throws "Reply already sent" error

### ISSUE THREAD

**Issue by mixecan** [fastify/fastify#1131]
In async route handlers `reply.send` can be used if no data is returned.
The same does not apply to the error handler function where this situation produces the log "Reply already sent".

```js
const fastify = require('fastify')
const server = fastify({
  logger: { level: "info", }
});

server.setErrorHandler(async (error, request, reply) => {
  reply.code(500).send("A very bad request!");
});

server.get("/bad", {}, async (request, reply) => {
  throw new Error();
});

server.get("/good", {}, async (request, reply) => {
  reply.code(200).send("ok");
  return;
});

server.listen(8000, '0.0.0.0')
  .then()
  .catch(err => {
    console.log(err);
    process.exit(1);
  });
```
```
{"level":40,"time":1535983157768,"msg":"Reply already sent","pid":60124,"hostname":"local","reqId":1,"type":"Error","stack":"Error: Reply already sent\n    at _Reply.Reply.send (~/Downloads/tmp/fastify-custom-handler-issue/node_modules/fastify/lib/reply.js:44:23)\n    at result.then.payload (~/Downloads/tmp/fastify-custom-handler-issue/node_modules/fastify/lib/reply.js:310:32)\n    at <anonymous>\n    at runMicrotasksCallback (internal/process/next_tick.js:121:5)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","v":1}
```

**Comment by mcollina** [comment]
To be correct, **this is not throwing**, this using an `async`  function calls the `reply.send()` function one time too much.

**Comment by mixecan** [comment]
You're right.
Bad choice of words 😄 

https://github.com/fastify/fastify/blob/cce1a8558196f23070a803150bfe9da4439535f5/lib/reply.js#L43-L46

**Comment by mcollina** [comment]
This is fixed in 1.11.2 https://github.com/fastify/fastify/pull/1134

**Comment by rwlaschin** [comment]
I'm still seeing the issue.  It seems to be calling the handler functions multiple times.  It could be a setup problem on my end so I'm including what I'm doing.  However I do print out when the routes are registered and this seems to happen only once.  Please note, **the middleware is only called once.**

    "fastify": "^1.13.4",
    "fastify-cookie": "^2.1.5",
    "fastify-formbody": "^2.0.3",
    "fastify-helmet": "^3.0.0",
    "fastify-static": "^1.1.0",

**I'm using to register to load my routes**
require('./routes').forEach(function ({ route, options }) {
    fastify.register(route, options);
});
**then functions like the following**
async function Render(fastify) {
    fastify.decorate('session', Session);

    const opts = {
        beforeHandler: fastify.session
    };

    [
        { type: 'get', path: '/api/practitioners', handler: practitioners, opts: opts },
        { type: 'get', path: '/api/practitioners/byZip/:zip', handler: notImplemented, opts: opts },
        { type: 'get', path: '/api/practitioners/byCity/:city', handler: notImplemented, opts: opts },
        { type: 'get', path: '/api/practitioner/:ids', handler: notImplemented, opts: opts },
        { type: 'get', path: '/api/practitioner/:ids/articles', handler: practitionerArticles, opts: opts },
        { type: 'get', path: '/api/practitioner/:ids/tips', handler: notImplemented, opts: opts },
        { type: 'get', path: '/api/practitioner/:ids/recommendation', handler: notImplemented, opts: opts },
        { type: 'get', path: '/api/practitioner/:ids/referral', handler: notImplemented, opts: opts },
    ].forEach(function (item) {
        Logger.info('Registering Route', item.type.toUpperCase(), module.exports.options.prefix, item.path);
        fastify[item.type](item.path, item.opts, item.handler);
    });
}

```[1548137073445] INFO  (37910 on Roberts-MacBook-Pro.local): incoming request
    reqId: 1
    req: {
      "id": 1,
      "method": "GET",
      "url": "/api/practitioner/24366,24372/articles?headingOnly=false",
      "hostname": "localhost:4000",
      "remoteAddress": "127.0.0.1",
      "remotePort": 61886
    }
[1548137073451] INFO  (37910 on Roberts-MacBook-Pro.local): localhost:4000
[1548137073451] INFO  (37910 on Roberts-MacBook-Pro.local): /api/practitioner/24366,24372/articles?headingOnly=false
[1548137073451] INFO  (37910 on Roberts-MacBook-Pro.local): {"headingOnly":"false"}
[1548137073451] INFO  (37910 on Roberts-MacBook-Pro.local): {"ids":"24366,24372"}
[1548137073451] INFO  (37910 on Roberts-MacBook-Pro.local): {"cache-control":"no-cache","postman-token":"59a8fce3-cd71-4174-bcf1-116f50fcef32","user-agent":"PostmanRuntime/7.6.0","accept":"*/*","host":"localhost:4000","cookie":"session=4p0cp9ntwjr6iw1bs","accept-encoding":"gzip, deflate","connection":"keep-alive"}
[1548137073451] INFO  (37910 on Roberts-MacBook-Pro.local): null
[1548137073452] DEBUG (37910 on Roberts-MacBook-Pro.local): Session key undefined
[1548137073454] INFO  (37910 on Roberts-MacBook-Pro.local): Query:  id,author,language,heading FROM Wholosophy.Content WHERE type = ? AND id in (?,?) LIMIT ?,? ["article","24366","24372","1",100]
[1548137073457] INFO  (37910 on Roberts-MacBook-Pro.local): Query:  id,author,language,heading FROM Wholosophy.Content WHERE type = ? AND id in (?,?) LIMIT ?,? ["article","24366","24372","1",100]
[1548137073491] INFO  (37910 on Roberts-MacBook-Pro.local): Practitioners []
[1548137073496] INFO  (37910 on Roberts-MacBook-Pro.local): request completed
    reqId: 1
    res: {
      "statusCode": 200
    }
    responseTime: 51.16854405403137
[1548137073499] INFO  (37910 on Roberts-MacBook-Pro.local): Practitioners []
[1548137073499] WARN  (37910 on Roberts-MacBook-Pro.local): Reply already sent
    reqId: 1
    err: {
      "type": "Error",
      "message": "Reply already sent",
      "stack":
          Error: Reply already sent
              at _Reply.Reply.send (/Users/rwlaschin/Work/Wholosophy/wholosophy-web/node_modules/fastify/lib/reply.js:63:30)
              at Object.send (/Users/rwlaschin/Work/Wholosophy/wholosophy-web/server/routes/practitioner.js:85:15)
              at tryCatch (/Users/rwlaschin/Work/Wholosophy/wholosophy-web/node_modules/regenerator-runtime/runtime.js:62:40)
              at Generator.invoke [as _invoke] (/Users/rwlaschin/Work/Wholosophy/wholosophy-web/node_modules/regenerator-runtime/runtime.js:288:22)
              at Generator.prototype.(anonymous function) [as next] (/Users/rwlaschin/Work/Wholosophy/wholosophy-web/node_modules/regenerator-runtime/runtime.js:114:21)
              at asyncGeneratorStep (/Users/rwlaschin/Work/Wholosophy/wholosophy-web/server/routes/practitioner.js:13:103)
              at _next (/Users/rwlaschin/Work/Wholosophy/wholosophy-web/server/routes/practitioner.js:15:194)
              at process._tickCallback (internal/process/next_tick.js:68:7)
    }
```

**Comment by mcollina** [comment]
I think you have something not correct in your `/api/practitioner/24366,24372/articles?headingOnly=false` route. I'm very confident in the current implementation (after this PR).

**Comment by rwlaschin** [comment]
You may be right.  I'd prefer the issue to be on my side.

The problem goes away when I remove the beforeHandler.

// error
fastify.get('/api/practitioner/:ids',{
    beforeHandler: fastify.session
}, practitionerById);

// no error
fastify.get('/api/practitioner/:ids',{}, practitionerById);

In the before Handler, I need to call next(), that is correct?

// This is what the middleware looks like
async function Session(request, reply, next) {
    let sessionId, response;
    try {
        sessionId = request.headers.session || request.param.session || request.cookie.session;
        if (sessionId) {
            response = await _Cache.get(`session.${sessionId}`);
        }
        request.session = response ? JSON.parse(response) : {};
    } catch (e) {
        /* eslint-disable-next-line no-emptyblock */
    } finally {
        Logger.debug('Session key', sessionId || '', response || '');
        next();
    }
}

**Comment by mcollina** [comment]
You should just remove the call to next. Either use an async function or call next.

**Comment by mcollina** [comment]
https://www.fastify.io/docs/latest/Hooks/ contains:

> the next callback is not available when using async/await or returning a Promise. If you do invoke a next callback in this situation unexpected behavior may occur, e.g. duplicate invocation of handlers.
