### ISSUE TITLE
ESLint error on async hooks

### ISSUE THREAD

**Issue by JbIPS** [fastify/fastify#4710]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

4.16.3

### Stopped working in version

4.17

### Node.js version

19.3.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Fedora 37

### 💥 Regression Report

This can look likes a game of cats and mouse but since the async typing on the hooks have been reverted  (#4708), ESLint validation fail :
```
error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
```

> Reverting back to how the route types were defined before, fixes this issue and appears to have no negative affects on any of the current tests. Added some for my use case to show how they do now work.

Clearlly the typing "works" because TS let it slides, but a closer look show the typings are wrong. But since its an ESLint reported issue, should I try to fix it without breaking #4705 ?

### Steps to Reproduce

* Create a route
* Add an async hook
* Run ESLint (extends 'standard-with-typescript', no additional rules)

### Expected Behavior

Async hooks property should accept promise-returning function (= AsyncHandler) so ESLint (or other strict type checker) would not throw error.

**Comment by lsnow99** [comment]
Hey just wondering if there is a PR to follow for this issue?

**Comment by JbIPS** [comment]
It's on my todo list but I didn't have time to start yet. Feel free to start a PR and I'll try to help :relaxed:

**Comment by thorhj** [comment]
I'm also running into this issue. For now I have to suppress the warning, or use a sneaky work-around I found. For some reason ESLint does not complain about the type mismatch if you wrap the function in an array 🤔 

```
onRequest: [myAsyncHookHandler] // no warnings
```

Probably the linting rule is not thorough enough to catch this.

**Comment by Uzlopak** [comment]
I think this got solved with #5147. Please comment if this happens after the next release.

**Comment by knicola** [comment]
I still see this error in at least 2 of my projects so far even after upgrading to `fastify@4.25.0`. If I patch `RouteShorthandOptions` to use `onErrorAsyncHookHandler`, instead of `onErrorMetaHookHandler`, eslint stops complaining.

**Comment by eKulshan** [comment]
Hey guys!
Still seeing this error on `fastify@4.28.1`
Here is the repro [repo](https://github.com/eKulshan/fastify-async-hook-type-error)

**Comment by TyIsI** [comment]
Confirmed in version 5.0.0.

Apparently it gets filtered out by the neostandard config:

I hot-patched the `eslint.config.js` as below and then it showed 28 instances of this error.

```
const tsConfigItem = module.exports.find(e => e.name === 'neostandard/ts')

tsConfigItem.rules['@typescript-eslint/no-misused-promises'] = 'error'
tsConfigItem.rules['@typescript-eslint/no-floating-promises'] = 'error'
tsConfigItem.languageOptions.parserOptions = {
  projectService: true,
  tsconfigRootDir: __dirname
}
```

```log
tyisi@beast:~/workspace/TyIsI/fastify(1)$ node_modules/.bin/eslint test/types/hooks.test-d.ts 

/home/tyisi/workspace/TyIsI/fastify/test/types/hooks.test-d.ts
  338:16  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  342:17  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  346:20  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  350:17  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  354:23  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  358:13  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  362:17  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  366:16  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  370:14  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  403:14  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  410:15  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  418:18  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  425:15  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  432:21  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  440:11  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  448:15  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  455:14  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  462:12  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  542:16  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  546:21  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  549:17  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  554:20  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  558:17  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  562:23  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  567:13  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  572:17  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  576:16  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  580:14  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises

✖ 28 problems (28 errors, 0 warnings)

tyisi@beast:~/workspace/TyIsI/fastify(1)$ 
```

It seems that it's in the various MetaHookHandler logic. I'm not well-versed enough with these kinds of constructs in TS to fully understand what's happening there.

Hope this helps and let me know if I need to create a new issue.

**Comment by mcollina** [comment]
The amount of wasted time due to those is enormous. However, I have a task on my list to actually flag the types for Fastify safe, so these would finally be gone.

**Comment by voxpelli** [comment]
> Apparently it gets filtered out by the neostandard config

Not really filtered out, rather that `neostandard` (at least for now) doesn’t have this rule and doesn’t do any type dependent linting. Feel free to add a request for it, but I’m skeptical of adding it since type dependent linting can scale rather badly with larger projects and projects with complex types.

**Comment by mcollina** [comment]
**let me say this one more time: none of those are issues, and they are false positives due to how Fastify is implemented**. Last month, the typescript-eslint team shipped the feature we need to account for them so that they won't be reported.

**Comment by TyIsI** [comment]
Copy

**Comment by voxpelli** [comment]
@TyIsI Fastify uses `tsd` instead of linting to verify that the types are correct :) And sounds like it won’t be possible to replicate this with `tsd`

@mcollina Are you aware of any issue in the typescript-eslint repo that’s related to this?

**Comment by hiranya911** [comment]
Just ran into this with with Fastify 5.3.3 on a project that also uses ESLint. It seems putting the handler inside an array (`preHandler: [custom()]`) as mentioned in a previous comment is a reasonable workaround. Curious to see how other devs get around this problem.
