### ISSUE TITLE
reply.code().send() does not infer correct type

### ISSUE THREAD

**Issue by pedroescumalha** [fastify/fastify#4883]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

4.18.0

### Stopped working in version

4.19.0

### Node.js version

18.16.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.2.1

### 💥 Regression Report

Upgrading from 4.18.0 to 4.19.x `reply.code().send()` can no longer infer the correct type if the provided type is an `Array<T>.` Seems to do with this commit: 7d02f769ee81abba336fd7a7988b0797a6948dfe. 

```
type ReplyTypeConstrainer<RouteGenericReply, Code extends ReplyKeysToCodes<keyof RouteGenericReply>, ReplyKey = CodeToReplyKey<Code>> =
  Code extends keyof RouteGenericReply ? RouteGenericReply[Code] :
    [ReplyKey] extends [never] ? unknown :
      ReplyKey extends keyof RouteGenericReply ? RouteGenericReply[ReplyKey] :
        unknown;
```

```
type TestReplyType = ReplyTypeConstrainer<string[], 200>; // TestReplyType is a string because it fulfils the first condition of ReplyTypeConstrainer
```

Is the intended behaviour to force users to implement the reply type as `{ [code: number]: any }`, or are users still allowed to provide any type as a reply?

### Steps to Reproduce

```
import fastify from '../fastify'

const server = fastify()

type TestResponse = string[];

server.get<{ Reply: TestResponse }>(
  '/ping',
  { schema: {} },
  async (request, reply) => {
    reply.code(200).send(['']) // type error
  }
)

server.listen({ port: 8080 }, (err, address) => {
  if (err) {
    console.error(err)
    process.exit(1)
  }
  console.log(`Server listening at ${address}`)
})
```

### Expected Behavior

The correct type should be inferred, or strict even more the reply type to be a Record<HttpStatusCode, unknown>.

**Comment by Uzlopak** [comment]
Maybe fixed with #4880

**Comment by pedroescumalha** [comment]
> Maybe fixed with #4880

Doesn't fix this issue. If RouteGenericReply extends an `Array<T>`, `Code extends keyof RouteGenericReply` will still be true and the resulting type will be `Array<T>[Code]`, which is `T`.
I can send a Pull Request to address this issue if you'd like.

**Comment by Uzlopak** [comment]
PR is welcome

**Comment by aadito123** [comment]
>resulting type will be Array<T>[Code], which is T

Looks like I missed this case in #4880 but I think checking for it with something like 
```typescript
RouteGenericReply extends Array<unknown> ? RouteGenericReply :
```
should fix it.

I guess another case where this would break is if someone wants the Reply type to be an object where the keys are HttpCodes. This would cause the .code().send() chain to infer incorrect types. Seems like a niche situation but idk if there is some escape hatch for it, other then not chaining the calls.

**Comment by sceccotti89** [comment]
Sorry to bother but I was wondering if there's any update on this issue. I'm currently unable to upgrade fastify to the latest version because of this (I'm currently stuck with version 4.18.0). I'm afraid this a bigger problem for new adopters, since they are forced to downgrade it to a working version.

**Comment by mcollina** [comment]
Shipping now

**Comment by algooru** [comment]
Still facing the same issue using version 4.21.0

**Comment by aadito123** [comment]
@algooru Can you provide a reproduction? Here is what I did in StackBlitz, and it had no type errors. https://stackblitz.com/edit/node-g81cyc?file=index.ts
