### ISSUE TITLE
Incorrect parsing of `hostname` on `FastifyRequest` when using IPv6

### ISSUE THREAD

**Issue by David-van-der-Sluijs** [fastify/fastify#5789]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0.0

### Node.js version

20.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Sequoia

### Description

This simple server:
```
import {fastify} from 'fastify';

const server = fastify({
    logger: true
});

server.get('/', (request, reply) => {
    console.log('Hostname: "' + request.hostname + '"');
    reply.send('Hello World!');
});

server.listen({port: 3040}, (err, address) => {
    console.log(`Server listening at ${address}`);
});
```

Prints:
```
Server listening at http://[::1]:3040
{"level":30,"time":1730060215348,"pid":34830,"hostname":"<redacted>","reqId":"req-1","req":{"method":"GET","url":"/","host":"[::1]:3040","remoteAddress":"::1","remotePort":63860},"msg":"incoming request"}
Hostname: "["
```

We can see that the hostname resolved to `[` which is wrong.

### Expected Behavior

The hostname should be `[::1]`.

**Comment by David-van-der-Sluijs** [comment]
I think the culprit is in [this line](https://github.com/fastify/fastify/blob/5927ca7957658c108d9fe4fdb06caef2aa0ddb90/lib/request.js#L223).

**Comment by David-van-der-Sluijs** [comment]
I've provided the fix and some further improvements as a pull request [here](https://github.com/fastify/fastify/pull/5790).

**Comment by mcollina** [comment]
should be fixed

**Comment by alipha** [comment]
@mcollina this issue was never fixed because the linked PR was closed without being merged.

Looks like the issue still exists in the code: https://github.com/fastify/fastify/blob/543f3410ba1db398e63a6603119eee971b9b6fc2/lib/request.js#L229
